# Generated by Django 3.2.10 on 2022-01-11 15:09
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pretalx_public_voting", "0002_publicvotingsettings"),
    ]

    operations = []
