# Generated by Django 3.2.10 on 2022-01-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretalx_public_voting", "0004_publicvotingsettings_allowed_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicvotingsettings",
            name="show_session_description",
            field=models.BooleanField(default=False),
        ),
    ]
