# Generated by Django 4.2.5 on 2023-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0073_track_position"),
        ("pretalx_public_voting", "0005_publicvotingsettings_show_session_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicvotingsettings",
            name="limit_tracks",
            field=models.ManyToManyField(to="submission.track"),
        ),
    ]
