# Generated by Django 4.2.5 on 2023-09-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submission", "0073_track_position"),
        ("pretalx_public_voting", "0006_publicvotingsettings_limit_tracks"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicvotingsettings",
            name="limit_submission_types",
            field=models.ManyToManyField(to="submission.submissiontype"),
        ),
    ]
